/**
 * Static perceptual-hash lookup over the pre-built Pokémon TCG
 * manifest at `assets/data/phash-manifest.json`.
 *
 * Generated by `scripts/build-phash-manifest.mjs`. Shipped inside the
 * JS bundle so every offline scan can short-circuit the network round-
 * trip when the user holds the phone over a well-known card.
 *
 * The manifest is loaded lazily on first lookup so cold-start is not
 * paid by users who never scan a card. The asset is `require()`d
 * synchronously by Metro the moment we touch it.
 *
 * If the manifest is absent (developer hasn't run the build script yet),
 * every method becomes a no-op — no crash, no warning at runtime.
 */
import { hammingDistance } from "./cardHashCache";

/** Shape mirrors what `build-phash-manifest.mjs` emits. */
export interface PhashEntry {
  cardId: string;
  name: string;
  number: string | null;
  setId: string | null;
  setName: string | null;
  imageUrl: string | null;
  rarity: string | null;
  dex: number | null;
}

interface PhashManifest {
  generatedAt: string;
  version: number;
  source: string;
  entries: Record<string, PhashEntry>;
}

// Tighter threshold than the user-cache (≤4 → ≤3). The static manifest
// is built from the OFFICIAL artwork, not the user's framing — a small
// distance budget keeps false positives at zero for visually similar
// cards (Pikachu vs Pikachu V, etc).
const STATIC_MATCH_DISTANCE = 3;

let loaded = false;
const entries: { hash: string; entry: PhashEntry }[] = [];

function ensureLoaded(): void {
  if (loaded) return;
  loaded = true;
  try {
    // Metro statically resolves the require at bundle time. If the
    // manifest hasn't been generated yet, the catch keeps us silent.
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const manifest: PhashManifest = require("../../../assets/data/phash-manifest.json");
    if (!manifest?.entries) return;
    for (const [hash, entry] of Object.entries(manifest.entries)) {
      if (typeof hash === "string" && hash.length === 16 && entry?.cardId) {
        entries.push({ hash, entry });
      }
    }
  } catch {
    // Manifest not built yet — that's fine, lookups will just miss.
  }
}

export interface StaticPhashHit {
  hash: string;
  distance: number;
  entry: PhashEntry;
}

export function lookupStaticPhash(hash: string): StaticPhashHit | null {
  if (!hash || hash.length !== 16) return null;
  ensureLoaded();
  if (entries.length === 0) return null;

  let bestDist = STATIC_MATCH_DISTANCE + 1;
  let best: { hash: string; entry: PhashEntry } | null = null;
  for (const e of entries) {
    const d = hammingDistance(hash, e.hash);
    if (d < bestDist) {
      bestDist = d;
      best = e;
      if (d === 0) break;
    }
  }
  if (!best) return null;
  return { hash: best.hash, distance: bestDist, entry: best.entry };
}

export function staticPhashSize(): number {
  ensureLoaded();
  return entries.length;
}
